# Page settings
baseurl      = "https://shklinkenberg.github.io/daa_site/docs/"
relativeURLs = true
title        = "De Amsterdamse Academie"
languageCode = "en-us"
theme        = "hugo-elate-theme"
publishDir   = "docs"
ignoreFiles  = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author      = "Klinkenberg"
  description = ""
  email       = "info@deamsterdamseacademie.nl"

  # Navigation
  [params.navigation]
    brand        = "DAA"
    home         = "Home"
    work         = "Faculteiten"
    testimonials = "Testimonials"
    services     = "Visie"
    about        = "Bestuur"
    contact      = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title    = "De Amsterdamse Academie"
    subtitle = 'medezeggenschapsvereniging aan de Universiteit van Amsterdam'
 
  # Intro section
  # Available icons: http://simpleicons.org/
  [params.intro]

  [[params.intro.item]]
    title = "Oprichting"
    description = "De Amsterdamse Academie is de eerste medezeggenschapsvereniging in Nederland."
    url         = "intro/oprichting/index.html"
    button      = "Meer weten"
    icon        = "icon-bulb"
    img         = "img_7.jpg"

  [[params.intro.item]]
    title       = "Werving"
    description = "Word lid van de medezeggenschapsvereniging De Amsterdamse Academie."
    url         = "intro/werving/index.html"
    button      = "Waarom DAA"
    icon        = "icon-heart"
    img         = "img_8.jpg"

  [[params.intro.item]]
    title = "OR leden"
    description = "Bekijk alle OR vertegenwoordigers van De Amsterdamse Academie."
    url         = "intro/orleden/index.html"
    button      = "OR leden"
    icon        = "icon-people"
    img         = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Faculteiten"
    description = "De Amsterdamse Academie is een nieuw opgerichte medezeggenschapsvereniging die op meerdere faculteiten meedoet aan de Ondernemingsraad verkiezingen. Wij staan voor een constructieve en kritische vorm van medezeggenschap, waarbij het welzijn van medewerkers en studenten voorop staat. Wij staan voor een universiteit die een inspirerend, dynamisch, academisch werkklimaat garandeert waarbinnen kwalitatief hoog academisch onderwijs en onderzoek worden gerealiseerd. Wij hechten aan een goede balans tussen 1e, 2e en 3e geldstroom activiteiten en pleiten voor een beargumenteerde afweging van onderwijs- en onderzoeksbelangen."
    footertext = ''

   [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "FNWI"
      var   = "fnwi"
      subtitle = "Lees hier de facultaire speerpunten"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = ""
      title = "FMG"
      var   = "fmg"
      subtitle = "Lees hier de facultaire speerpunten"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "FGw"
      var   = "fgw"
      subtitle = "Lees hier de facultaire speerpunten"
      
    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "ACTA"
      var   = "acta"
      subtitle = "Speerpunten"      

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "GOR"
      var   = "gor"
      subtitle = "Speerpunten"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Redenen om je aan te sluiten bij De Amsterdamse Academie."

    [[params.testimonials.item]]
      quote = "&ldquo;We bundelen onze krachten. Bij de vorige verkiezingen bleek het zelf samenstellen van niet-vakbondslijsten erg ingewikkeld. De vereniging DAA heeft de know-how, en aansluiten bij de DAA heeft als voordeel dat je je alleen hoeft te concentreren op de kandidaten en het formuleren van een programma (binnen de kaders van de uitgangspunten van DAA).&rdquo;"
      person = 'Gerwin van der Pol<span class="subtext">Voorzitter</span>'
      img = "gerwin.jpg"
      alt = "Gerwin"

    [[params.testimonials.item]]
      quote = "&ldquo;Ik heb niet zo veel met de vakbonden, maar wil me wel graag verenigen in het streven naar een gezonde universiteit met een constructief kritische medezeggenschap.&rdquo;"
      person = 'Sharon Klinkenberg <a href="https://www.linkedin.com/in/sharonklinkenberg/" target="_blank"><i class="icon-linkedin"></i></a><span class="subtext">Kandidaat FMG</span>'
      img = "sharon.jpg"
      alt = "Sharon"

#    [[params.testimonials.item]]
#      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
#      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
#      img = "person3.jpg"
#      alt = "Person3"
  



  # Services section
  [params.services]
    enable = true
    title = "Visie"
    description = "De vereniging ‘de Amsterdamse Academie’ wil vertegenwoordigd worden in ondernemingsraden van de UvA vanuit een kritisch constructieve visie. Zij wil hiermee een alternatief bieden voor de lijsten die ontstaan zijn naar aanleiding van de Maagdenhuisbezetting van 2015 en de traditionele vakbondslijsten. In 2018 zullen nieuwe verkiezingen plaatsvinden. De Amsterdamse Academie wil in alle faculteiten aan deze verkiezingen deelnemen."

    [[params.services.item]]
      title = "Onderwijs &amp; Onderzoek"
      description = "Idealiter is het grootste deel van de medewerkers van de UvA vooral bezig met onderzoek en onderwijs. Het bestuur is in handen van academici met veel ervaring in onderwijs en onderzoek, ondersteund door een efficiënte professionele staf. Het bestuur is vooral ondersteunend. Zij creëert de beste omstandigheden voor goed onderwijs en onderzoek, zoals goede voorzieningen en een eerlijk, transparant en stabiel verdelingsmodel voor de middelen. Zij schept een dynamisch academisch klimaat waarin onderwijsverbetering en onderzoeksontwikkeling vooral ‘bottom up’ plaatsvinden."
      icon = "icon-book-open"

    [[params.services.item]]
      title = " Gezonde Universiteit"
      description = "De Amsterdamse Academie streeft naar een gezonde universiteit die in al haar disciplines tot de Europese top behoort, met een goede balans tussen eerste, tweede en derde geldstroom activiteiten en tussen onderwijs- en onderzoeksbelangen. De Amsterdamse Academie streeft ook naar een verstandig personeelsbeleid waarin de belangen van het vaste personeel, tijdelijk personeel en toekomstig personeel goed zijn afgewogen. De Amsterdamse Academie is niet voor grote veranderingen in de Wet op Universitair bestuur (WUB). We gaan uit van het huidige efficiënte besturingsmodel waarin we voldoende mogelijkheden zien voor een universitaire structuur waarin eenheden die goed onderwijs verzorgen, een goed onderzoeksprogramma kennen en voldoende 1e, 2e en/of 3e geldstroominkomsten verwerven, grotendeel zelfstandig over de inrichting van hun werkzaamheden kunnen beslissen."
      icon = "icon-heart"
      
    [[params.services.item]]
      title = "Kwalitatief hoog academisch onderwijs"
      description = "De Amsterdamse Academie streeft naar hoog kwalitatief academisch onderwijs voor alle studenten in een actieve onderzoeksomgeving. We laten ons hierbij leiden door zo objectief mogelijke beschikbare criteria: Onderwijs- en onderzoeksvisitaties, succes in de verwerving van 2e en 3e geldstroom, vergelijking met resultaten in andere universiteiten, en verschillende monitoren van onderwijskwaliteit (NSE, UvA-Q). Dit geldt ook het personeelsbeleid. Belangrijk is de medewerkersmonitor om een beeld te krijgen van algemene tevredenheid van medewerkers. De Amsterdamse Academie is ook pragmatisch. We zullen lobbyen voor meer geld voor academisch onderzoek en onderwijs maar aanvaarden ook de uitkomsten van verdeelmodellen. Onderzoek en onderwijs zal moeten plaatsvinden binnen bepaalde financiële kaders."
      icon = "icon-like"

      [[params.services.item]]
      title = "Toekomstige Bestuurders"
      description = "De UvA heeft net als vele andere onderwijs- en onderzoeksinstellingen moeite goede bestuurders te vinden op elk niveau. De Amsterdamse Academie stelt zich daarom ook ten doel toekomstige academische bestuurders op te leiden. We verwachten dat deelname van talentvolle jonge academici aan de ondernemingsraden hierbij een grote rol kan spelen. Juist jonge onderzoekers/docenten waarvan de verwachting is dat ze over enige jaren door zullen groeien naar hogere academische rangen zouden in de ondernemingsraden ervaring met academisch bestuur op moeten doen. De Amsterdamse Academie wil daarom ook een rol spelen in de opleiding van de leden van de ondernemingsraden."      
      icon = "icon-pencil"

  # About section
  [params.about]
    enable = true
    title = "Bestuur"
    description = "Er is een bestuur nodig om de vereniging op de rit te krijgen en houden, maar de vereniging bestaat vooral voor en door de leden. Op het platform en tijdens de jaarlijkse Algemene Ledenvergadering hebben de leden inspraak."

    [[params.about.item]]
      name = "Gerwin van der Pol"
      position = "voorzitter"
      description = ""
      img = "gerwin.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Annemie Ploeger"
      position = "secretaris"
      description = ""
      img = "annemie.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]   
      
        [[params.about.item]]
      name = "Robert Zwitser"
      position = "penningmeester"
      description = ""
      img = "robert.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "https://twitter.com/RobertZwitser"],
        ["icon-facebook", "#"],
        ["#0077B5", "#"]
      ]
      
      [[params.about.item]]
      name = "Cees Kleverlaan"
      position = "algemeen bestuurslid"
      description = ""
      img = "cees.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]
    
          [[params.about.item]]
      name = "Han van der Maas"
      position = "algemeen bestuurslid"
      description = ""
      img = "han.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]    
      
  

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable      = true
    map         = false
    form        = false
    title       = "Laat van je horen"
    description = "Heb je vragen opmerkingen of suggesties, laat het ons dan gerust weten."
    
    # Available icons: http://simplelineicons.org/
    details = [
        ["icon-home", "Gustav Mahlerlaan 3004 – 11n69<br>1081 LA Amsterdam"],
        # ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "<a href='mailto:info@deamsterdamseacademie.nl'>info@deamsterdamseacademie.nl</a>"],
        # ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "https://www.facebook.com/DeAmsterdamseAcademie/"],
        ["icon-youtube", "#youtube"]
      ]
