---
title      : "Kandidaten"
author     : "Gerwin van der Pol"
date       : 2016-05-10T12:12:12-05:00
weight     : 3
subsection : kandidaten
---

# Kandidaten OR-verkiezingen 2024

In het voorjaar van 2024 vinden bij vier faculteiten OR-verkiezingen plaats. Dit zijn de kandidaten die zich namens De Amsterdamse Academie verkiesbaar hebben gesteld:

<!-- Button stem reminder 

<div style="width:100%; text-align: center">
<a style="margin:10px;" href="Stemmen_op_DAA.ics" class="btn btn-primary"><i class="icon-calendar"></i> Stem DAA reminder</a> 
</div>

<style>
.grid-container {
  display: flex;
  flex-wrap: wrap;
}
.grid-item {
  width: 350px;
  margin: 20px;
  font-size: 30px;
  text-align: left;
}
-->

</style>

<div class="grid-container">
  <div class="grid-item">

[FNWI](#fnwi)
[FMG](#fmg)
[FGw](#fgw)
  
## FNWI {.fnwi}

### Wouter Waalewijn (UDH Institute of Physics)

Ik doe onderzoek in theoretische deeltjesfysica, en ben inmiddels ruim acht jaar werkzaam aan de UvA. Mijn eerste termijn in de OR zit er bijna op, waarvan ongeveer de helft als lid van het dagelijks bestuur (DB). In het begin voelde de OR vrij reactief: we stelden vragen naar aanleiding van stukken die op tafel kwamen, maar het was vaak te laat in het proces om nog invloed te hebben. Ik heb mij ingezet voor een actieve rol: het identificeren van aandachtspunten, het schrijven van ongevraagde adviezen en eerder betrokken zijn in de besluitvorming. Ik wil mij hiergraag voor blijven inzetten.

### Chris Stolk (Associate professor bij het Korteweg-de Vries Instituut)

Als lid van de ondernemingsraad werk ik samen met de andere leden om voorgesteld beleid te toetsen. Ik vind het belangrijk dat de instituten optimaal worden ondersteund bij het realiseren van de doelstellingen van goed onderwijs en onderzoek. Als OR lid, kijk ik samen met de andere leden, naar een goede balans tussen diverse belangen, zoals die van medewerkers en studenten, het belang van goed onderwijs en onderzoek en het belang van de faculteit en universiteit.

### David Dubbeldam (Universitair Hoofddocent)

De huidige tijd kenmerkt zich vooral door introductie van nieuwe technieken zoals Artificial Intelligence. De ontwikkelingen gaan zo snel dat hierover zorgen bestaan bij studenten en op de werkvloer. Ik wil me inzetten om structurele oplossingen te vinden. Door de introductie van ChatGPT zullen er veel slagen moeten worden gemaakt om het onderwijs toekomstbestendig te maken. Er moet een balans komen waar alle docenten en studenten zich in kunnen vinden en samen een grote update en modernisatie van het onderwijs uitgevoerd gaat worden.

### Leendert Hamoen (Hoogleraar Algemene Microbiologie)

Ik ben werkzaam bij het Swammerdam Institute for Life Sciences (SILS) als hoogleraar microbiologie en wil mij de komende jaren inzetten voor een goede ondersteuning van onderzoek en onderwijs. Het stijgend aantal studenten, de sterke internationalisering van onderzoek en onderwijs, de toenemende complexiteit en kosten van onderzoek en de verregaande samenwerkingen tussen onderzoekers brengt grote uitdagingen met zich mee. Dit vereist een dynamische, ambitieuze en vooruitkijkende universiteit, die een goede balans nastreeft tussen onderzoek en onderwijs, en de bureaucratische belasting minimaliseert. De OR kan hier een positieve bijdrage aan leveren en hier zou ik mij graag voor willen inzetten.
  
  </div>
  <div class="grid-item">
  
## FMG {.fmg}

### Tessa van Schijndel (Universitair docent Onderwijswetenschappen)

De OR legt ervaringen en zorgen van medewerkers neer bij de decaan waardoor hun stem wordt gehoord en meegenomen in beleidsontwikkeling en -uitvoering. De afgelopen termijn heb ik me als OR-lid op een kritische, maar ook constructieve manier ingezet voor een helder, bij de ervaringen van medewerkers aansluitend, personeelsbeleid met transparante procedures. Ook heb ik me hard gemaakt voor het realiseren van structurele werkdrukverlaging en een inclusieve faculteit waarin alle medewerkers zich thuis voelen, autonomie ervaren en gelijke kansen krijgen. Ik zou me hier graag voor blijven inzetten!

### Annemie Ploeger (Docent bij Psychologie)

Met veel plezier ben ik OR-lid bij de FMG namens De Amsterdamse Academie (DAA). Ik heb mij de afgelopen jaren met name beziggehouden met het thema ‘werkdruk’. Mede door de OR zijn de afdelingen van FMG nu bezig met het maken van concrete plannen om de werkdruk te verlagen. Ik wil mij heel graag de komende drie jaar op een kritisch constructieve manier inzetten om deze plannen werkelijkheid te laten worden. Ik werk als docent bij de afdeling Psychologie en doe, naast het geven van onderwijs, onderzoek naar depressie en welzijn van studenten. Ook ben ik sinds zes jaar actief lid van het bestuur van DAA. Wil je met mij over de werkdrukplannen of andere OR-zaken praten? Ik ben te bereiken via: a.ploeger@uva.nl

### Jan Henk Kamphuis (Hoogleraar Klinische Psychologie)

Met >20 jaar in diverse functies bij de afdeling Psychologie van de UvA heb ik aanzienlijke en diverse (administratieve) ervaring opgedaan die me goed van pas kan komen om me nuttig te maken bij de Ondernemingsraad. Als hoogleraar Individual Differences ben ik van nature geneigd autonomie, vertrouwen en de erkenning van het individu hoog te waarderen. Beleid en procedures kunnen nuttige instrumenten zijn, maar mogen niet zelf het doel worden. Of, zoals een voormalig FMG-decaan het zei over richtlijnen: naleven, of uitleggen. Met andere woorden, richtlijnen zijn precies dat, verlies er niet het individu mee uit het oog, en gun medewerkers zoveel mogelijk vertrouwen.

### Annabeth Groenman (Universitair Docent Preventieve Jeugdhulp en opvoeding)

Sinds 2019 werk ik op de UvA. Eerst als postdoc onderzoeker, later als universitair docent. Naast dat ik lesgeef, doe ik ook onderzoek naar autisme, ADHD en gedragsstoornissen. Ik stel mij verkiesbaar voor de OR omdat ik het belangrijk vind dat medewerkers invloed hebben op de beslissingen die genomen worden. Belangrijke thema’s voor mij zijn werkdruk, duurzaamheid, en inclusiviteit. Ook vind ik het belangrijk dat iedere medewerker de kans en tijd krijgt om diens talenten in het werk te ontwikkelen. Ook wil ik meer leren over hoe de beleids- en besluitvorming op een universiteit precies plaatsvindt. Mijn focus ligt op het begrijpen van beleidsvorming en het actief deelnemen aan besluitvorming.

### Sharon Klinkenberg (Docent bij Communicatiewetenschap)

Met een groot hart voor onderwijs, een progressieve kijk op onderzoek en scherp inzicht in onderwijs-organisatorische processen, wil ik mij de komende jaren constructief en kritisch inzetten voor de OR aan de FMG. Mijn rollen als docent, onderzoeker en onderwijs-ondersteuner hebben me een brede blik gegeven op onze organisatie. Waar we naar mijn idee meer behoefte aan hebben is: op elk niveau goed academisch leiderschap en veel betere interne communicatie. Dat loopt uiteen van een eerlijke en transparante verdeling van de middelen binnen de FMG tot doceerbaarheid van het onderwijs. Ik wil me hier namens medezeggenschapsvereniging De Amsterdamse Academie voor inzetten.


  </div>  
  <div class="grid-item">
  
## FGw {.fgw}

### Gerwin van der Pol (Docent Mediastudies FGw)

Medezeggenschap betekent voor mij: vanuit goede dossierkennis alle geluiden, meningen binnen de FGw horen en een stem geven om via discussie tot een zo goed mogelijk beleid voor de FGw uit te komen. Grote kwesties om aan te pakken zijn: de druk op internationaliseren, financierbaarheid van de FGw, overbelasting van het obp en regeldruk. Dat alles onder de druk van het debat over wereldwijde conflicten en crises, dat ook bepaalt wat we als echte academische gemeenschap van studenten, docenten, onderzoekers en obp willen zijn.

### Vesna Vravnik (Docent Media Studies)

Na ruim zes jaar een tijdelijk contract te hebben gehad, heb ik dankzij een nieuw onderwijsbeleid een vaste aanstelling gekregen. Dankbaar voor de rol van de OR in de beleidsvorming ben ik bij de tussentijdse verkiezingen van 2022 in het team gekomen. Hoewel het beleid een aanzienlijke vooruitgang betekent, is het niet de eindbestemming. Een aanzienlijk aantal faculteitsleden heeft nog steeds te maken met onzekere arbeidssituaties. Als OR-vertegenwoordiger zal ik blijven pleiten voor meer vaste aanstellingen. Ik zal ook manieren zoeken om de kloof tussen docenten en wetenschappers te overbruggen voor een meer inclusieve academische omgeving, waarbij initiatieven voor diversiteit, genderevenwicht, sociale veiligheid en internationalisering prioriteit krijgen.

### Kimberly Poole (ambtelijk secretaris)

Mijn kennis reikt verder dan de FGw alleen, zo heb ik rechten gestudeerd aan de FdR en werkte ik tijdens mijn studie bij het SIC. De afgelopen twee jaar was ik ambtelijk secretaris van de EC voor het cluster Media en sinds vorig jaar ben ik assistent teamleider van het secretariaat. Ik begrijp dat er momenten zijn dat de OR het verschil kan uitmaken en wil op die momenten het belang van het OBP vertegenwoordigen door op kritische en constructieve wijze invloed uit te oefenen op de gang van zaken binnen de organisatie. Mijn doel hierin is het verbeteren van een betrokken en inclusieve werkomgeving voor iedereen. Ik ben bekend met complexe regelgeving en mensen die mij kennen weten dat ik uitdagingen aanpak. Ik ben vastbesloten om de stem van het OBP te laten horen en bij te dragen aan kansengelijkheid en diversiteit binnen de UvA.

### David Hollanders (Docent)

Sinds 2017 doceer ik economie bij Europese Studies, waarbij ik mij inhoudelijk eerst en vooral richt op monetair beleid in de eurozone. Sedert 2022 ben ik lid van de ondernemingsraad. Mijns inziens is de primaire taak van de ondernemingsraad de borging van belangen van werknemers. En werknemers zijn gebaat bij vaste contracten en vermindering van onderlinge concurrentie om onderzoektijd en/of bevorderingen.
  
   </div>
<div class="grid-item">
  
  </div>
</div>











