---
title      : "Oprichting"
author     : "Gerwin van der Pol"
date       : 2016-05-10T12:12:12-05:00
weight     : 3
subsection : oprichting
---

# Medezeggenschapsvereniging De Amsterdamse Academie

De vereniging ‘De Amsterdamse Academie’ wil actief deelnemen aan ondernemingsraden van de UvA op een kritische en constructieve wijze. Zij wil hiermee een alternatief bieden voor de verkiezingslijsten die ontstaan zijn naar aanleiding van de Maagdenhuisbezetting van 2015 en de traditionele vakbondslijsten.

De UvA heeft net als vele andere onderwijs- en onderzoeksinstellingen moeite goede bestuurders te vinden op elk niveau. De Amsterdamse Academie stelt zich daarom ook ten doel toekomstige academische bestuurders op te leiden.

De Amsterdamse Academie is de eerste medezeggenschapsvereniging in Nederland en is opgericht op 24 oktober 2017 door wetenschappelijk medewerkers die meer zeggenschap willen over het onderwijs en onderzoek in hun eigen werkomgeving.

<a style="margin:10px;" href="../../statuten_DAA.PDF" class="btn btn-primary"><i class="icon-doc"></i> Statuten</a>