---
title      : "OR leden"
author     : "Sharon Klinkenberg"
date       : 2016-05-10T12:12:12-05:00
weight     : 3
subsection : orleden
---

# Overzicht DAA-leden in de ondernemingsraden

De onderstaande collega's zijn namens De Amsterdamse Academie vertegenwoordigd in de ondernemingsraden van de UvA. 

<style>
.grid-container {
  display: flex;
  flex-wrap: wrap;
}
.grid-item {
  width: 350px;
  margin: 20px;
  font-size: 30px;
  text-align: left;
}

</style>

<div class="grid-container">
  <div class="grid-item">
  
## OR - Bestuursstaf en centrale eenheden (GOR)

* <a href="http://www.uva.nl/profiel/k/r/i.kraal/i.kraal.html">Irene Kraal
  
  </div>
  <div class="grid-item">
  
## OR - FNWI

* <a href="http://www.uva.nl/profiel/s/m/i.smallegange/i.smallegange.html">Isabel Smallegange
* <a href="http://www.uva.nl/profiel/w/i/r.a.d.wijnands/r.a.d.wijnands.html">Rudy Wijnands
* <a href="http://www.uva.nl/profiel/h/a/l.w.hamoen/l.w.hamoen.html">Leendert Hamoen
* <a href="http://www.uva.nl/profiel/c/o/g.l.corthals/g.l.corthals.html">Garry Corthals
* <a href="http://www.uva.nl/profiel/s/p/r.j.c.spreeuw/r.j.c.spreeuw.html">Robert Spreeuw
* <a href="http://www.uva.nl/profiel/d/e/m.p.decowski/m.p.decowski.html">Patrick Decowski
* <a href="http://www.uva.nl/profiel/n/i/t.m.nieuwenhuizen/t.m.nieuwenhuizen.html">Theo Nieuwenhuizen
  
  </div>
  <div class="grid-item">
  
## OR - FMG 

* <a href="http://www.uva.nl/profiel/z/w/r.j.zwitser/r.j.zwitser.html">Robert Zwitser
* <a href="http://www.uva.nl/profiel/k/l/s.klinkenberg/s.klinkenberg.html">Sharon Klinkenberg</a>

  </div>  
  <div class="grid-item">
  
## OR - FGw

* <a href="http://www.uva.nl/profiel/p/o/g.w.vanderpol/g.w.vanderpol.html">Gerwin van der Pol
* <a href="http://www.uva.nl/profiel/s/c/j.schoo/j.schoo.html">Janneke Schoo
* <a href="http://www.uva.nl/profiel/l/a/f.laroui/f.laroui.html">Fouad Laroui
* <a href="http://www.uva.nl/profiel/m/a/j.m.a.h.maessen/j.m.a.h.maessen.html">Enno Maessen
* <a href="http://www.uva.nl/profiel/b/e/j.j.bekkenkamp/j.j.bekkenkamp.html">Jonneke Bekkenkamp
  
    </div>
  <div class="grid-item">
  
## OR - ACTA

* <a href="http://www.uva.nl/profiel/k/l/c.kleverlaan/c.kleverlaan.html">Cees Kleverlaan
* <a href="http://www.uva.nl/profiel/s/l/m.sluijs/m.sluijs.html">Marian Sluijs
  
  </div>
</div class="grid-item">

## Centrale Ondernemingsraad (COR)

* <a href="http://www.uva.nl/profiel/p/o/g.w.vanderpol/g.w.vanderpol.html">Gerwin van der Pol
* <a href="http://www.uva.nl/profiel/k/r/i.kraal/i.kraal.html">Irene Kraal
* <a href="http://www.uva.nl/profiel/k/l/c.kleverlaan/c.kleverlaan.html">Cees Kleverlaan
* <a href="http://www.uva.nl/profiel/s/l/m.sluijs/m.sluijs.html">Marian Sluijs
* <a href="http://www.uva.nl/profiel/b/e/j.j.bekkenkamp/j.j.bekkenkamp.html">Jonneke Bekkenkamp

  
  </div>
</div>











