# Privacy verklaring 

De Amsterdamse Academie, gevestigd aan Gustav Mahlerlaan 3004 -- 11n69
1081 LA Amsterdam, is verantwoordelijk voor de verwerking van
persoonsgegevens zoals weergegeven in deze privacyverklaring.

Contactgegevens:

-   https://www.deamsterdamseacademie.nl
-   Gustav Mahlerlaan 3004 - 11n69 1081 LA Amsterdam

## Persoonsgegevens die wij verwerken

De Amsterdamse Academie verwerkt uw persoonsgegevens doordat u gebruik
maakt van onze diensten en/of omdat u deze zelf aan ons verstrekt.
Hieronder vindt u een overzicht van de persoonsgegevens die wij
verwerken:

-   Voor- en achternaam
-   E-mailadres
-   werkzaam bij UvA/ faculteit/ afdeling

## Bijzondere en/of gevoelige persoonsgegevens die wij verwerken

Onze website en/of dienst heeft niet de intentie gegevens te verzamelen
over websitebezoekers die jonger zijn dan 16 jaar. Tenzij ze toestemming
hebben van ouders of voogd. We kunnen echter niet controleren of een
bezoeker ouder dan 16 is. Wij raden ouders dan ook aan betrokken te zijn
bij de online activiteiten van hun kinderen, om zo te voorkomen dat er
gegevens over kinderen verzameld worden zonder ouderlijke toestemming.
Als u er van overtuigd bent dat wij zonder die toestemming persoonlijke
gegevens hebben verzameld over een minderjarige, neem dan contact met
ons op, dan verwijderen wij deze informatie.

## Met welk doel en op basis van welke grondslag wij persoonsgegevens verwerken

De Amsterdamse Academie verwerkt uw persoonsgegevens voor de volgende
doelen:

-   Het registreren van uw lidmaatschap
-   Verzenden van onze nieuwsbrief en/of reclamefolder

De Amsterdamse Academie verwerkt uw gegevens over de werkplek om inzicht
te hebben over de verdeling van de leden over de verschillende
faculteiten met het oog op de verkiezingen.

## Geautomatiseerde besluitvorming

De Amsterdamse Academie neemt niet op basis van geautomatiseerde
verwerkingen besluiten over zaken die (aanzienlijke) gevolgen kunnen
hebben voor personen. Het gaat hier om besluiten die worden genomen door
computerprogramma's of -systemen, zonder dat daar een mens (bijvoorbeeld
een medewerker van De Amsterdamse Academie) tussen zit. De Amsterdamse
Academie gebruikt de volgende computerprogramma's of -systemen: MS forms
en outlook, voor de registratie van het lidmaatschap en het versturen
van leden informatie.

## Hoe lang we persoonsgegevens bewaren

De Amsterdamse Academie bewaart uw persoonsgegevens niet langer dan
strikt nodig is om de doelen te realiseren waarvoor uw gegevens worden
verzameld. Wij hanteren de volgende bewaartermijnen voor de volgende
(categorieën) van persoonsgegevens:

-   persoonsgegevens \> Bewaartermijn: tot 2 maanden na afloop
    lidmaatschap\> Reden 1, 2
-   Adresgegevens \> Bewaartermijn: tot 2 maanden na afloop
    lidmaatschap\> Reden 1,2
-   E-mailadres\> Bewaartermijn: tot 2 maanden na afloop lidmaatschap\>
    Reden 1,2
-   werkzaam bij UvA/ faculteit/ afdeling\> Bewaartermijn: tot 2 maanden
    na afloop lidmaatschap\> Reden 6

Uitleg bovenstaande redenen:

1: Toestemming: De betrokkene heeft toestemmingen gegeven voor de
verwerking van zijn persoonsgegevens voor een of meer specifieke
doeleinden. 2: Overeenkomst: De verwerking is noodzakelijk voor de
uitvoering van een overeenkomst waarbij de betrokkene partij is, of om
op verzoek van de betrokkene vóór de sluiting van een overeenkomst
maatregelen te nemen. 6: Gerechtvaardigd belang: De verwerking is
noodzakelijk voor de behartiging van de gerechtvaardigde belangen van de
verwerkingsverantwoordelijke of van een derde, behalve wanneer de
belangen of de grondrechten en de fundamentele vrijheden van de
betrokkenen die tot bescherming van persoonsgegevens nopen, zwaarder
wegen dan die belangen, met name wanneer de betrokkene een kind is.

## Delen van persoonsgegevens met derden

De Amsterdamse Academie verstrekt uitsluitend aan derden en alleen als
dit nodig is voor de uitvoering van onze overeenkomst met u of om te
voldoen aan een wettelijke verplichting.

## Cookies, of vergelijkbare technieken, die wij gebruiken

De Amsterdamse Academie gebruikt geen cookies of vergelijkbare
technieken.

## Gegevens inzien, aanpassen of verwijderen

U heeft het recht om uw persoonsgegevens in te zien, te corrigeren of te
verwijderen. Daarnaast heeft u het recht om uw eventuele toestemming
voor de gegevensverwerking in te trekken of bezwaar te maken tegen de
verwerking van uw persoonsgegevens door De Amsterdamse Academie en heeft
u het recht op gegevensoverdraagbaarheid. Dat betekent dat u bij ons een
verzoek kunt indienen om de persoonsgegevens die wij van u beschikken in
een computerbestand naar u of een ander, door u genoemde organisatie, te
sturen. U kunt een verzoek tot inzage, correctie, verwijdering,
gegevensoverdraging van uw persoonsgegevens of verzoek tot intrekking
van uw toestemming of bezwaar op de verwerking van uw persoonsgegevens
sturen naar a.ploeger@uva.nl of g.w.vanderpol@uva.nl. Om er zeker van te
zijn dat het verzoek tot inzage door u is gedaan, vragen wij u een kopie
van uw identiteitsbewijs met het verzoek mee te sturen. Maak in deze
kopie uw pasfoto, MRZ (machine readable zone, de strook met nummers
onderaan het paspoort), paspoortnummer en Burgerservicenummer (BSN)
zwart. Dit ter bescherming van uw privacy. We reageren zo snel mogelijk,
maar binnen vier weken, op uw verzoek. De Amsterdamse Academie wil u er
tevens op wijzen dat u de mogelijkheid heeft om een klacht in te dienen
bij de nationale toezichthouder, de Autoriteit Persoonsgegevens. Dat kan
via de volgende link:
https://autoriteitpersoonsgegevens.nl/nl/contact-met-de-autoriteit-persoonsgegevens/tip-ons

## Hoe wij persoonsgegevens beveiligen

De Amsterdamse Academie neemt de bescherming van uw gegevens serieus en
neemt passende maatregelen om misbruik, verlies, onbevoegde toegang,
ongewenste openbaarmaking en ongeoorloofde wijziging tegen te gaan. Als
u de indruk heeft dat uw gegevens niet goed beveiligd zijn of er
aanwijzingen zijn van misbruik, neem dan contact op met
<a.ploeger@uva.nl> of <g.w.vanderpol@uva.nl>.
