---
title      : "Werving"
author     : "Gerwin van der Pol"
date       : 2016-05-10T12:12:12-05:00
weight     : 3
subsection : kandidaten
---

# Waarom De Amsterdamse Academie

Waarom de medezeggenschapsvereniging De Amsterdamse Academie? Bij de ondernemingsraadsverkiezingen van 2015 waren er 164 mensen die zich verkiesbaar hadden gesteld voor 89 zetels. Er waren vier verschillende lijsten, FNV universiteiten, VAWO, de Vrije Lijsten en Rethink. De meerderheid van de medezeggenschap binnen de UvA is georganiseerd vanuit de klassieke vakbonden, maar er is ook een grote groep mensen die zich niet aangesproken voelt door een vakbond, maar zich wel wil inzetten voor medezeggenschap binnen de UvA. Wij willen met jullie een platform ontwikkelen om binnen de universiteit de beste omstandigheden voor goed onderwijs en onderzoek, met goede voorzieningen en ondersteuning te creëren.

Waarom een medezeggenschapsvereniging en niet een vakbond? De vakbonden onderhandelen over de primaire en secundaire arbeidsvoorwaarden en komen dus op voor het werknemersbelang. Dit doen ze via de VSNU en het lokaal overleg met het bestuur. Daarnaast zijn ze in meerderheid in de lokale medezeggenschap vertegenwoordigd. De agenda van de ondernemingsraden wordt vaak bepaald  werknemers belangen en gaat nauwelijks over de inhoud van het werk, namelijk goed onderwijs en onderzoek. De medezeggenschapvereniging De Amsterdamse Academie richt zich op de inhoud van onze universiteit waardoor het onderwijs en onderzoek beter wordt en onze functie leuker. Wij gaan voor kritische MEDEzeggenschap!