---
title      : "FGW Speerpunten"
author     : "Gerwin van der Pol"
date       : 2016-05-10T12:12:12-05:00
weight     : 3
subsection : FGW_speerpunten
---

# FGW Speerpunten

Binnen de FGw willen wij de nadruk leggen op de menselijke maat. De papieren werkelijkheid van beleidsdocumenten spoort vaak niet met de ervaring van individuele medewerkers. Onze faculteit staat op alle terreinen onder druk: werkdruk, regeldruk, machtsongelijkheid en demonisering van afwijkende standpunten. Tegelijkertijd is de kracht van onze faculteit de tomeloze energie van medewerkers, collegialiteit en kritische dialoog, geloof in de waarde van de Geesteswetenschappen en openheid naar de samenleving. 

Als leden van de Amsterdamse Academie pleiten wij: 

* voor een eerlijke verhouding tussen werklast en inkomen voor alle medewerkers,
* voor meer diversiteit en  kansengelijkheid  in het facultaire personeelsbeleid
* voor samenwerking en tegen polarisatie,
* voor eerlijke en realistische kansen voor onze jongste generatie medewerkers

Een stem op ons is een stem op de relatief meest diverse lijst. Wij willen bouwen aan een faculteit die vertrouwt op de kracht en expertise van iedereen, vaste en tijdelijke medewerkers, promovendi en buitenpromovendi. Een faculteit die ons allemaal de vrijheid en rust biedt om te floreren.
