---
title      : "FMG Speerpunten"
author     : "Gerwin van der Pol"
date       : 2016-05-10T12:12:12-05:00
weight     : 3
subsection : FMG_speerpunten
---

# Eerlijk en transparant allocatiemodel binnen FMG

Onlangs is er binnen de UvA een nieuw allocatiemodel vastgesteld. Dit model bepaalt o.a. hoeveel geld er naar elk van de faculteiten gaat. Het is nu aan de FMG om te bepalen hoeveel geld iedere afdeling krijgt. De DAA is voor een eerlijk en transparant allocatiemodel waarbij niet alleen wordt gekeken naar de omvang van de afdelingen, maar ook naar de aard van werkzaamheden (bijv. type onderzoek) en de kosten die dat met zich meebrengt. 

# Goed inzicht in toekomstige financiële ontwikkelingen

De afdelingen binnen FMG leken verrast door de financiele tekorten. Hoe komt dat? Had FMG niet eerder kunnen weten dat de inkomsten terug zouden lopen? En hadden we niet eerder inzicht kunnen krijgen in de kosten voor het komende jaar? Het lijkt erop dat met name de kosten in toekomstige uitgaven voor verrassingen hebben gezorgd. De DAA wil kritisch kijken naar de huidige gang van zaken en zich inzetten voor een goed inzicht in toekomstige inkomsten en uitgaven.

# Decentrale medezeggenschap

Binnen de FMG wordt veel georganiseerd en besloten binnen de vier afdelingen, maar de OR is georganiseerd op faculteitsniveau. De DAA is van mening dat een deel van het OR-werk beter tot zijn recht komt als het wordt belegd in deelraden of -commissies die op afdelingsniveau overleggen met het afdelingsbestuur. Wat de DAA betreft hoort hier ook een goede samenwerking met de opleidingscommissie (OC) bij.  

# Doceerbaarheid van het onderwijsprogramma

Er is terecht veel aandacht voor de studeerbaarheid van ons onderwijsprogramma. Maar naast de studeerbaarheid wil de DAA ook aandacht hebben voor de doceerbaarheid van het programma. De werkdruk is al hoog en de aankomende bezuinigingen moeten niet simpelweg leiden tot hetzelfde werk in minder tijd. De DAA wil zich graag inzetten voor het bedenken van slimme, efficiënte oplossingen. 
